### PR TITLE
new loader option for pk type uuid (doc table)

### PR DESCRIPTION
**Pull request by lfurzewaddock**
I need this option, similar to issue #501 for a current project, so thought I would contribute my effort so far.

Unfortunately, my previous T-SQL experience didn't help much when trying to add conditional logic with PL/pgSQL. I eventually gave in and simply copied the existing query file: `document-table.sql`, included some small changes and added the conditional logic to 'lib/database.js' instead.

Perhaps @dmfay you might be able to assist?

I did have trouble with the test suite too, with about 30 tests stubbornly failing, although apart from a couple of tests searching for an id using the integer 1 rather than for an id using a uuid string I think my changes are OK, although a little rough.

### CODE REVIEW

**Comment by lfurzewaddock** [comment]
Notes for commit 16299946fbfa6c74ef994296a4f0c0983f7fcd13

We cannot create extension "uuid-ossp" in a query file without giving the database account used by the app, superuser privileges.

A better/more secure way is to use a superuser account to create the extension for the whole database, so the extension is available to the app, without it requiring superuser access.

These are the steps I followed;

```
$ psql -d postgres -h localhost -p 5432 -U postgres
psql (10.4 (Ubuntu 10.4-2.pgdg16.04+1))
Type "help" for help.

postgres=# \c YOUR_DB_NAME;
You are now connected to database "YOUR_DB_NAME" as user "postgres".
YOUR_DB_NAME=# CREATE EXTENSION "uuid-ossp";
CREATE EXTENSION
YOUR_DB_NAME=# \q
```

**Comment by lfurzewaddock** [comment]
Thanks @dmfay for taking the time to review my rough PR!

> Yeah, you can't run PLPGSQL flow control statements outside the context of a function. It should be possible to avoid duplicating the script using pg-promise's raw text interpolation though! 

OK, I've manged as you said to alter the original doc table script to take a column data type name and a raw value for the default statement. Internally, I'm using a switch to generate the default statement, to mitigate the use of a raw value here.

I had some problems removing the CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; from the doc table script, which you may have noticed from a previous commit/comment requires the app to have superuser privileges, which for me is a show stopper (although would pass tests as they are executed using the postgres account). 

I realised the global.resetDb was probably removing the uuid-ossp extension I had previously added manually to the db following the steps;

```
$ psql -d postgres -h localhost -p 5432 -U postgres
psql (10.4 (Ubuntu 10.4-2.pgdg16.04+1))
Type "help" for help.

postgres=# \c YOUR_DB_NAME;
You are now connected to database "YOUR_DB_NAME" as user "postgres".
YOUR_DB_NAME=# CREATE EXTENSION "uuid-ossp";
CREATE EXTENSION
YOUR_DB_NAME=# \q
```

Therefore, I added a new db.createExtension method and call this inside global.resetDb which seems to work. I'm not a 100% sure if you will find this acceptable or agree with the implementation. Please advise if there is a better way that does not require the app to connect to the db with superuser privileges.

> v1mc UUIDs are more efficiently indexed than v4 UUIDs so the default should be uuid_generate_v1mc() for best performance

I have some concerns relating to setting a default to something less secure, although I've just noticed you advise v1mc, not v1 (which the tests are currently running). I would expect most people including me ;-) to not properly investigate the options and simply leave the default as is, ignorant of any implications. However, to accommodate, I've added a new setting `verUUID` which makes choosing the preferred UUID type easy and perhaps we could make use of the `uuid_nil` which generates a UUID only containing zeros for testing.

Quick ref: [Which UUID version to use?](https://stackoverflow.com/questions/20342058/which-uuid-version-to-use/20342413#20342413)

> the option name is a bit verbose: documentPkType gets the point across imo. Just default that to serial and make sure to set the default when it's uuid

Done.

> instead of changing all document tables created during testing and dealing with all the fallout from that, just add a single new test to test/connect.js that sets documentPkType, creates a document table, and verifies that a new record has a UUID primary key

I've copied the test file `/test/database/saveDoc.js`, renamed the copy to `/test/database/saveDoc-uuid.js`

In the new file I have replaced the two previously failing tests asserting id to be 1 with regex tests to validate if the id is a valid UUID.

**Comment by dmfay** [comment]
Okay, quite a bit going on here, let's dig in :)

## Extension
In testing, `resetDb` drops all non-system schemas and the extension goes with them. In production, you should have any extensions you need installed _before_ you spin up your application; like you noticed, if you've got your app user permissions set up appropriately it won't be able to create an extension at runtime. And of course it's less than ideal to create the extension in the script if you aren't using UUID keys anywhere.

Bottom line I don't see `db.createExtension` getting a lot of production use but it's not hurting anything. You don't need to `then` off `this.query` though, since that already returns a promise. Otherwise :+1: 

## UUID versions
`verUUID` is on the obtuse side; `uuidVersion` would be clearer.

`getDefaultSQLForUUID` expects users to read the uuid-ossp docs to find out which particular function name they want; I'd rather hide that and offer `v1`, `v1mc`, and so on to make that more straightforward. The documentation (docs/documents.md) needs to explain how to use UUID keys and list the available types too, and a note about using v4 for randomness vs v1mc for performance would also be good to have.

The constant-returning functions like `uuid_nil` and the `uuid_ns_*` set are essentially useless for primary keys so there's no need to include those. Nil is sometimes useful in testing but in my experience it's been used to pregenerate a single entity's PK; there's no point in hardcoding a table-level default to straight zeroes.

## Tests
`saveDoc` is an extra degree out from where the action's happening. What this needs is a new test in test/database/createDocumentTable.js that ensures invoking `createDocumentTable` with the UUID key configuration really does create a table that sets UUID keys. Create a table, save a document, check the key.

This way you also avoid modifying the global loader which could potentially result in a lot of extra noise if something goes horribly wrong later on ;)

**Comment by lfurzewaddock** [comment]
OK @dmfay, getting close - touching less files!

## Extension

Agreed: `db.createExtension` and now `db.dropExtension` are present to support tests and constraints created by the test environment. 

> You don't need to then off this.query though, since that already returns a promise. Otherwise 👍

Oops and done. 

## UUID versions
> verUUID is on the obtuse side; uuidVersion would be clearer.

Done.

> getDefaultSQLForUUID expects users to read the uuid-ossp docs to find out which particular function name they want; I'd rather hide that and offer v1, v1mc, and so on to make that more straightforward. 

There may be a misunderstanding here, probably due the chosen function name. I've simplified the uuidVersion arguments required, if that's what you meant? To clarify; its purpose is to set the constant containing the SQL string/statement to be inserted directly into the raw placeholder within the query file. It protects against typos, injection and sets the default (recommended) setting. _Currently it is set to v4 - please confirm which version you want?_ It does not require any input from devs leaving it set to the default, but accommodates devs who have done some research and wish to prioritise performance over security etc.

> The documentation (docs/documents.md) needs to explain how to use UUID keys and list the available types too, and a note about using v4 for randomness vs v1mc for performance would also be good to have.

I will look at the docs and add some notes/links, but would like the code implementation agreed first in case there are any further changes.

> The constant-returning functions like uuid_nil and the uuid_ns_* set are essentially useless for primary keys so there's no need to include those. Nil is sometimes useful in testing but in my experience it's been used to pregenerate a single entity's PK; there's no point in hardcoding a table-level default to straight zeroes.

OK, I've removed ` uuid_ns_*` options, but left `uuid_nil` for potential testing purposes. I can also remove that if your prefer?

## Tests
> saveDoc is an extra degree out from where the action's happening. What this needs is a new test in test/database/createDocumentTable.js that ensures invoking createDocumentTable with the UUID key configuration really does create a table that sets UUID keys. 

OK, I've copied 2 existing tests in `test/database/createDocumentTable.js` and modified them to use UUID config.

> Create a table, save a document, check the key the way you've already got.

OK, I've deleted `test/database/saveDoc-uuid.js` and copied 2 existing tests in `test/database/saveDoc.js`, modified them to use UUID config, and test the automatically generated UUID is valid.

**Comment by dmfay** [comment]
re getDefaultSQLForUUID: that's exactly what I meant -- there's enough research involved in knowing whether you want v1 or v4 or whatever without needing to track down the exact name of the function that generates that type of UUID in Postgres!

There are good arguments for both v4 and v1mc as the default so I'm fine with v4 winning that one. I _did_ just have the thought that it could potentially be reduced to a single configuration parameter -- so if you set (spitballing) documentPkType = `v4` it's a v4 UUID, with the default still being `SERIAL`. You've almost certainly put more thought into this than I have, so what's your take on that idea vs a UUID flag + separate version specification?

`uuid_nil` just isn't useful for testing: if you set that as the table-level default, you can only ever insert one record without having to specify a pk value yourself, which defeats the purpose of defaults. So let's pull that one out too.

As far as the tests: what you've got in the createDocumentTable tests now confirms that the table exists, but doesn't actually test the PKs of a stored record. If you save a document and test for a UUID key there, I don't think you need to touch the `saveDoc` tests at all -- the createDocumentTable tests will have proved it out sufficiently.

**Comment by lfurzewaddock** [comment]
> There are good arguments for both v4 and v1mc as the default so I'm fine with v4 winning that one.

OK, agreed. I think it's the safest/best option for a default/recommended setting.

> I did just have the thought that it could potentially be reduced to a single configuration parameter -- so if you set (spitballing) documentPkType = v4 it's a v4 UUID, with the default still being SERIAL. 

IMO, its best to leave it as documentPkType = 'uuid'. That will make more sense to devs who may not even know there are different uuid variations to choose from. Also, there are other pg extensions other than 'uuid-ossp' which may require alternate variation names.

> uuid_nil just isn't useful for testing: if you set that as the table-level default, you can only ever insert one record without having to specify a pk value yourself, which defeats the purpose of defaults. So let's pull that one out too.

Done.

> As far as the tests: what you've got in the createDocumentTable tests now confirms that the table exists, but doesn't actually test the PKs of a stored record. If you save a document and test for a UUID key there, I don't think you need to touch the saveDoc tests at all -- the createDocumentTable tests will have proved it out sufficiently.

I'm slightly concerned by adding saveDoc to createDocumentTable tests I am mixing otherwise separated concerns, but accept your judgement, so it's done.

**Comment by dmfay** [comment]
Looks great! Just add some user information to docs/documents.md and this is good to go :)

**Comment by dmfay** [comment]
I've just published 5.1.0 -- thanks for contributing!

**Pull request merged**
