### PR TITLE
First stab at promises doc

### PR DESCRIPTION
**Pull request by retorquere**

### CODE REVIEW

**Comment by retorquere** [comment]
I've gone for yield over .then

**Comment by dmfay** [comment]
Thanks for going to the trouble on this! `yield` is nonstandard, unfortunately; tons of people use co but it's not something I want to assume. Ideally `await` would have dropped earlier, but as it is substituting that would also leave a ton of users behind. `.then(...)` is annoying but it's the formulation most generally compatible.

In your connection examples it looks like you're storing the connection promise rather than the connected database, which you get by yielding whenever you query. That's suboptimal; better to `massive(...).then(db => { app.set('db', db); ... })`.

**Comment by retorquere** [comment]
The problem for my specific case is that I'll be using the database connection in more than one file, and I don't want to connect to the database separately in all of them. A resolved promise yields very quickly (certainly under bluebird). But I wouldn't want to argue that this needs to be a universal preference.

**Comment by dmfay** [comment]
I meant 'suboptimal' in terms of it being an extra step to go through; as far as I know, you're correct that the performance implications are negligible. Since you're already storing _something_ for later retrieval, there's no reason for that to be anything other than the database driver itself instead of the promise. You just have to make sure you `listen` or what have you in the promise callback or after `yield`ing/`await`ing.

**Comment by retorquere** [comment]
I will have one module which sets up the database connection and exports the promise; other modules can then import that module and take it from there. I wouldn't know how to set up that kind of system otherwise. Something like

```
massive(...).then(db => { app.set('db', db); ... })
```

may have other parts of the express app accessing `app.get('db')` before the promise was resolved. By exporting the promise I get predictable behavior.

**Comment by dmfay** [comment]
There's nothing to `app.get` before the server starts listening. You can take advantage of this by listening at the end of an asynchronous process:

```js
const app = express();
const server = http.createServer(app);

massive('').then(db => {
  app.set('db', db);

  server.listen(3000);
});
```

You can of course connect in another function or another module so long as you return a promise from it and `listen` in the promise callback, but you shouldn't need to import it anywhere else in most cases -- that's why you `app.set` and `app.get` it in the first place.

**Comment by retorquere** [comment]
Ah, I see now. Hmm. I'll keep that in mind, but I also have non-express files (such as cronjob tasks) that include the db setup module.

**Comment by dmfay** [comment]
That's exactly the kind of special case I was thinking about :) There's ways to go about that (personally, I'd question whether it belongs in the webapp module or should be broken out into a separate process) but the readme needs to target a simple, general case.

**Comment by retorquere** [comment]
Fair enough.

**Pull request closed without merging**
