### PR TITLE
Add validation option to saveDoc

### PR DESCRIPTION
**Pull request by retorquere**
This way you can do some schema validation before it hits the database

### CODE REVIEW

**Comment by retorquere** [comment]
Frick, something went wrong. The previous merge wasn't in this.

**Comment by retorquere** [comment]
OK, got it.

**Comment by dmfay** [comment]
Validation is a huge, huge can of worms in terms of project scope. Fundamentally it's not what I envision for Massive: its purpose is to move data around, not to define what that data should be. That's why it introspects your tables instead of making you write models, for example. Protecting the user from her- or himself is a job for a different tool, and there are plenty of feature-rich validation libraries to choose from (shameless plug -- I even [wrote my own](https://github.com/dmfay/corro) at one point!).

**Comment by retorquere** [comment]
Fair enough. I wasn't looking for massive to do validation though, I was looking for massive to allow validation (plugging in corro or validate.js should you so want). I can get around it with hooker.

**Comment by retorquere** [comment]
I take it then you also wouldn't be interested in allowing findDoc to return an object with methods from a prototype applied? I can do that with hooker too.

**Comment by dmfay** [comment]
Yeah, that's also something you should be doing in client code if you need it imo.

**Pull request closed without merging**
