### PR TITLE
Increase the capacity that select the internal value of the JSONB field and can rename the selected field

### PR DESCRIPTION
**Pull request by muguang-lijing**
Increase the capacity that select the internal value of the JSONB field and can rename the selected field
I think this feature is necessary, and it's very common. I often need it on my projects.

### CODE REVIEW

**Comment by robertrossmann** [comment]
Would be great to have some tests added for this feature...

**Comment by robertrossmann** [comment]
Also, there is a bunch of linter errors:

```
/home/travis/build/dmfay/massive-js/lib/statement/select.js
   91:7    error    'the_columns' is never reassigned. Use 'const' instead  prefer-const
   92:31   warning  Missing space before function parentheses               space-before-function-paren
   92:33   warning  A space is required after ','                           comma-spacing
   92:36   warning  Missing space before opening brace                      space-before-blocks
   93:9    error    'dot_index' is never reassigned. Use 'const' instead    prefer-const
   94:26   warning  Missing space before opening brace                      space-before-blocks
   95:11   error    'col_infos' is never reassigned. Use 'const' instead    prefer-const
   96:48   warning  A space is required after ','                           comma-spacing
   96:96   warning  Infix operators must be spaced                          space-infix-ops
   96:111  warning  A space is required after ','                           comma-spacing
   97:25   warning  Missing space before opening brace                      space-before-blocks
   98:37   warning  A space is required after ','                           comma-spacing
  100:7    warning  Expected blank line before this statement               padding-line-between-statements
  100:28   warning  Infix operators must be spaced                          space-infix-ops
```

**Comment by muguang-lijing** [comment]
I tested it locally. I've fixed that internal bug. In fact, that internal error is a strict syntax check. It can also run but the 'const' declaration have better performance

**Comment by dmfay** [comment]
hi, thanks for contributing! Aliasing fields in generated queries has been a bit of a weak point so I'm glad it's getting some love. I do have concerns about the string-parsing approach, though: this code looks like it doesn't account for edge cases where field names or aliases contain whitespace or punctuation. You've also reproduced some of the `parseKey` logic to generate the `#>>` traverser arguments; I don't think this will execute the way you intended since the `Select` constructor passes `fields` through `parseKey`, which replaces the JSON punctuation with proper traversers before anything reaches `format()` (including for array elements).

I think a better way to do this would be to allow `options.fields` to be an object `{alias: 'mycolumn', theAttr3: 'jsonbField3.attr2[0].attr3'}`. This could be processed in the `Select` constructor just like `exprs` is, except the values go through `parseKey` to turn them into valid column names or JSON elements.

**Comment by dmfay** [comment]
Closing due to inactivity. If you (or anyone else) are still interested in aliasing `options.fields` feel free to open a new pull request.

**Pull request closed without merging**
