### PR TITLE
Expose the Database class

### PR DESCRIPTION
**Pull request by robertrossmann**
This PR achieves the following:

- It moves the `connection` object sanitisation into _lib/database.js_ and makes the main `massive()` constructor function a thin wrapper around creating this class (this expands on work already done in #449)
- Removes the check for `connection` object being defined and instead relies on the default values defined in `pg` (assumes a local postgres instance)
- Unrelated - adds the ability to re-generate API docs without `jsdoc` being installed globally
- Finally exposes the Database class as part of the public API so that consumers of this library can, if they so choose, import the `Database` class themselves and instantiate it on their own, leaving the responsibility to call `.reload()` in their own hands (this is the **primary purpose** of this PR)

#### TODOs

- There are some warnings in the test suite now, I guess it's because massive now connects to two different databases during the test suite (the _massive_ db and _travis_ db, which is the default used when no connection info is specified) - I am unsure how to fix those warnings and how severe those warnings are

Let me know what you think, looking forward to hearing your feedback!

### CODE REVIEW

**Comment by dmfay** [comment]
This looks fine, thanks for contributing! Re documentation, I've basically automated it with npm scripts. `build/apidocs.sh` runs before every version update. If you just want to see what the JSDoc you write will look like, you can do this:

```
rm -rf ./docs/api

jsdoc -d ./docs/api -c ./.jsdoc.json -r
```

Removing that extra check sounds good too, I didn't realize node-pg had made it redundant.

**Comment by vitaly-t** [comment]
> Finally exposes the Database class as part of the public API so that consumers of this library can, if they so choose, import the Database class themselves and instantiate it on their own, leaving the responsibility to call .reload() in their own hands (this is the primary purpose of this PR)

By the way, class [Database] was designed as the main integration point, so any library can take it as a parameter. I even wrote some documentation on it, see [Integration]. This is why the object contains such important properties as [$config], [$pool] and [$cn].

[Integration]:https://github.com/vitaly-t/pg-promise/wiki/Integration
[Database]:http://vitaly-t.github.io/pg-promise/Database.html
[$config]:http://vitaly-t.github.io/pg-promise/Database.html#$config
[$pool]:http://vitaly-t.github.io/pg-promise/Database.html#$pool
[$cn]:http://vitaly-t.github.io/pg-promise/Database.html#$cn

**Comment by robertrossmann** [comment]
Thanks guys for your comments! I have updated this PR with updated docblocks and removed the check for `connection` object. I have updated the initial PR's description with new entries:

- Removes the check for `connection` object being defined and instead relies on the default values defined in `pg` (assumes a local postgres instance)
- Unrelated - adds the ability to re-generate API docs without `jsdoc` being installed globally

**Notes**

- The docblock for the now-exposed `Database` class is not linked to it's definition - I could not figure out a way to link it properly
- There are some warnings in the test suite now, I guess it's because massive now connects to two different databases during the test suite (the _massive_ db and _travis_ db, which is the default used when no connection info is specified) - I am unsure how to fix those warnings and how severe those warnings are

**Comment by dmfay** [comment]
I don't want to leave you hanging here but things have gotten super hectic for me. With any luck I'll be able to take a look at this over the weekend and figure out what's going on with the duplicate QueryFile warnings in the test output; they're not really worrying, but I'd definitely prefer not to have them. Regarding the docblock, have you tried using the `@module` directive?

**Comment by vitaly-t** [comment]
> what's going on with the duplicate QueryFile warnings in the test output

I wouldn't worry much about it. pg-promise in its own tests lets it happen all over, because those are tests. In fact, it passes in option `noWarnings: true` to avoid warnings in tests.

**Comment by dmfay** [comment]
I figured out what was going on with jsdoc -- helps if your class is named the same thing as the file it's in! I didn't have much luck with the warnings but that's no big deal.

**Comment by robertrossmann** [comment]
Thanks for review and merging! And good find on that JSDoc behaviour.

By the way, I would love to see this PR released to npm so I can start working on a feature which requires the `Database` class in my own project. Thanks!

**Comment by dmfay** [comment]
I want to get #440 done first so all the breaking changes come in at once, but that shouldn't take me long at all. Look for it in the next day or so. If you want to get a head start, [you can track `master` in your package.json](https://docs.npmjs.com/files/package.json#github-urls).

**Comment by robertrossmann** [comment]
Thanks, I will do that for now!

> PS. This PR should not break any code. All the changes are backwards-compatible with current 3.x release line.

**Comment by dmfay** [comment]
This one is, but I've been working on stuff that isn't -- right now `master` contains major changes to traversing JSON fields that aren't compatible with v3.

**Comment by dmfay** [comment]
v4 is taking a little longer than I anticipated, so I cherry-picked a bunch of stuff and released v3.3.0.

**Comment by robertrossmann** [comment]
Just saw the release notification. Awesome, thanks! ❤️

**Pull request merged**
