### PR TITLE
upgrading to pg-promise 6.5.0

### PR DESCRIPTION
**Pull request by vitaly-t**
Corrects this PR: https://github.com/dmfay/massive-js/pull/446

### CODE REVIEW

**Comment by dmfay** [comment]
awesome, thanks! & yeah I should go clean up the `^`s. Theoretically breaking changes shouldn't happen with minor versions but I can't exactly cast the first stone with regard to rigorously adhering to semver either ;)

**Comment by j0k3r** [comment]
Great to see that fixed, I was about to yell at vitaly-t/pg-promise about introducing a breaking change in a minor version.
@dmfay could you release a patch/minor version with that upgrade? Thanks!

**Comment by vitaly-t** [comment]
@j0k3r be nice, don't yell :smile: 

I initially did that breaking change in 7.x, but since I got stuck with 7.x, and its release date is unknown, I did it as 6.5.0, because that change is so long overdue.

**Comment by j0k3r** [comment]
I was about to yell because we lost few hours on friday debugging `TypeError: script.sql.formatDBType is not a function` :slightly_smiling_face: 

I think you should have deprecate the old function instead of removing it.

**Comment by vitaly-t** [comment]
@j0k3r oh I see. Massive now uses `~` for its dependencies, which is a good safe practice. Lots of packages get broken on minor version unintentionally, or worse - on builds. One such terrible example - [pg-query-stream](), the guys wrote the whole thing from scratch, and then upped it to `1.1.0` from `1.0.0`, which is another reason 7.x got stuck.

Anyhow, sorry for the trouble, I haven't done broken changes in pg-promise in minor version since its inception, will remember not to do it again.

**Comment by vitaly-t** [comment]
@dmfay I start to think it may cause problems for anyone using the latest Massive 3.2.1 which use pg-promise reference as `^6.4.0`. Maybe you should release an update asap.

Damn it, I will never release a breaking change again :smile:

**Comment by dmfay** [comment]
3.2.2 is out!

**Comment by vitaly-t** [comment]
Looking at this release note:

> If you've been wondering what formatDBType is, grab the upgrade!

...made me realize that [Custom Type Formatting](https://github.com/vitaly-t/pg-promise#custom-type-formatting) documentation isn't good, so I've just rewritten it from scratch, because it is the most powerful feature in the query-formatting engine.

**Pull request merged**
