### PR TITLE
chore: Update to node 10 in .travis.yml

### PR DESCRIPTION
**Pull request by dmfay**

### CODE REVIEW

**Comment by vitaly-t** [comment]
Hah, it's never gonna happen. Travis CI PostgreSQL upgrade path was and remains piss-poor.

**Comment by dmfay** [comment]
Node 10, not Postgres 10 :) I'm waiting for https://github.com/nodejs/node/issues/20503 to release, until then streams are broken.

**Comment by vitaly-t** [comment]
@dmfay Wasn't it fixed by now? :wink:

**Comment by dmfay** [comment]
It was! It also exposed another bug in my testcases that took entirely too long to work out :woman_facepalming:

**Pull request merged**
