### PR TITLE
Refactor index.js to allow multiple connections, async startup, cleaner bootstrapping

### PR DESCRIPTION
**Pull request by benjie**
This is the refactoring changes from #295 with an improvement (and test) to loading `db/query.sql` and `db/query/file.sql` both.
- Factors out the global `self` variable in index.js which allows you to `massive.connect` to multiple databases without as many issues as before
- Refactors `walkSqlFiles` to be asynchronous for consistency
- Splits `connect` into two phases: the collection phase: `bootstrap` (which queries the database, filesystem, etc); and the initialisation phase: `initialize` (which takes the data from the collection phase and applies it to the local instance)
- Fixes the missing error handler [here](https://github.com/robconery/massive-js/blob/75b9208acdcc41b59a27152b1520a06cdc1f92e4/index.js#L477-L478)
- Uses `fs.stat` rather than extension/error to see if paths are files/directories
- Fixes the issues of having both `db/query.sql` and `db/query/file.sql` - now deterministically loads both queries rather than the previous behaviour which would have one or the other win based on the filesystem order
- **[BREAKING]** Prevents SQL files from overwriting existing methods
  - Warns the user via either console.warn or a custom notifier if there's a clash
  - No longer deletes built in functions if they share a name with a script source folder

### CODE REVIEW

**Comment by benjie** [comment]
@robconery / @dmfay Any thoughts on this PR?

**Comment by dmfay** [comment]
You add `var self = this;` at a few points and don't seem to use it, and I think you can take away the 'would love to be refactored' comment on `walkSqlFiles`! Other than that I'm good, but since the behavior when loading files is different I'll defer to Rob on pulling it in.

**Comment by robconery** [comment]
There is a lot going on with this and it makes me nervous. I'm wondering if this can be pushed to v3? I need to get that rolling (hopefully in the next month or so) and the main thing I want to avoid is a major change to v2 that will break things that we need to support.

Just to be clear: the driver for this change is multiple connections?

**Comment by benjie** [comment]
The main driver is to allow lightweight cloning of massive instances to enable #295 (connection wrapper to enable local variables in transactions for every query) and similar functionality others may wish to introduce; the multiple connections thing is just a side benefit that I've not tested yet.

Your response is definitely fair - the diffs do seem quite daunting, but thankfully that's just a façade!
Other than making walkSqlFiles asynchronous it's really just re-arranging the code you already have and splitting bootstrapping into two phases; e.g.

- instead of loading each thing in turn, we fetch each thing and then apply our learnings all at once:

screen shot 2016-08-09 at 18 27 50

- fetching is just the first half of loading; e.g. for functions:

screenshot 2016-08-09 18 33 00

- applying the loaded functions is identical (but at a significantly reduced indentation level):

screenshot 2016-08-09 18 34 29

I'm happy to give this treatment to all the changes if it's helpful (or to split them into separate commits to make it easier to review, maybe?). Hopefully you can see from this that there's not much actual change going on, it's mostly just moving code around, so shouldn't break anything sensible.

The only breaking change that it has, as far as I'm aware, is that naming one of your SQL files in such a way as to overwrite a built in method is now no longer allowed - but I'm not sure that should have been allowed in the first place (I think it's an accidental feature?). I'm happy to revert this so that the functions can be overwritten if you want...


As you may have noticed, I'm invested in the future of Massive.js (since I'm using it for one of my projects) so I'm keen to keep my version as close to yours as possible - let me know how I can make your life easier with my changes and I'll do my best 😄 . I did dip my toes in the bluebird branch too (since I'd like to use async/await) but I got scared and ran away.

**Comment by robconery** [comment]
Cheers - thanks so much for the lengthy reply :). Let me download and stare at it for a bit. The biggest thing for me is losing touch with the codebase - which I suppose is already happening anyway.

I can get to this over next weekend.

**Comment by benjie** [comment]
@robconery I'm not sure if you got a chance to look at this PR in the end; but I've just rebased it on the latest master so it's merge-able again (hopefully).

**Comment by benjie** [comment]
I've rebased this on the latest master, @robconery have you had any further thoughts on this?

**Comment by dmfay** [comment]
@benjie I like where you're going with this, but my first priority right now is wrapping up v3 so I'd rather not pull anything big into master in the mean time. If you have the time/inclination do check out the `promises` branch, though!

**Comment by looking-promising** [comment]
@benjie Thanks for adding support for multiple dbs -- it is exactly what I need.  What did you end up doing?  Are you just running off your own fork?

**Comment by dmfay** [comment]
Closing out legacy PRs.

**Pull request closed without merging**
